//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TanarKilistazo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TanarKilistazoEntities : DbContext
    {
        public TanarKilistazoEntities()
            : base("name=TanarKilistazoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Felhasznalok> Felhasznalok { get; set; }
        public virtual DbSet<Osztalyok> Osztalyok { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tanarok> Tanarok { get; set; }
        public virtual DbSet<Tantargyak> Tantargyak { get; set; }
        public virtual DbSet<Tantermek> Tantermek { get; set; }
        public virtual DbSet<Orarendek> Orarendek { get; set; }
    }
}
